# Generated by Django 5.2.3 on 2025-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="issue_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
