# Generated by Django 5.2.3 on 2025-06-16 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_expense_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
