# Generated by Django 5.2.3 on 2025-07-17 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_alter_expense_issue_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="periodicity",
            field=models.CharField(
                choices=[("O", "One time"), ("R", "Recurrent")],
                default="O",
                help_text="Select if recurrent payment",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="expenses", to="tracking.category"
            ),
        ),
    ]
